### ISSUE TITLE
Tối ưu hiệu suất trang chủ cho website thương mại điện tử

### ISSUE THREAD

**Issue by HDV2k3** [NamDuongPham/Shopee#7]
Mô tả:
Trang chủ của website thương mại điện tử hiện đang gặp phải tình trạng tải chậm, ảnh hưởng đến trải nghiệm người dùng. Cần phân tích và tối ưu hiệu suất tổng thể của trang này.

Các vấn đề hiện tại:
Thời gian tải trang (Page Load Time): Trang chủ mất hơn 5 giây để tải trên thiết bị di động.
Kích thước file JavaScript: Bundle JS hiện tại quá lớn (~1.5MB), ảnh hưởng đến tốc độ tải.
Hình ảnh chưa được tối ưu: Một số hình ảnh trên trang chủ có kích thước lớn, cần được tối ưu để giảm kích thước mà vẫn giữ chất lượng.
Không sử dụng Lazy Load cho hình ảnh: Các hình ảnh sản phẩm và banner đang tải toàn bộ ngay từ đầu, gây chậm trang.
Render lại quá nhiều lần (Re-renders): Có dấu hiệu rằng một số component đang bị render lại không cần thiết, gây tiêu tốn tài nguyên và làm chậm UI.
Công việc cần thực hiện:
 Phân tích và tối ưu hóa bundle JS bằng cách sử dụng code splitting và dynamic imports.
 Tối ưu hóa hình ảnh bằng cách nén và sử dụng các định dạng hiện đại như WebP.
 Thêm Lazy Loading cho các hình ảnh không nằm trong vùng hiển thị ban đầu (viewport).
 Kiểm tra các component nào đang bị render lại quá nhiều lần và tối ưu lại logic render.
 Kiểm tra và áp dụng kỹ thuật memoization (React.memo, useMemo, useCallback) nếu cần để giảm thiểu render không cần thiết.
Môi trường:
Phiên bản React: ^18.x
Thiết bị: Desktop, Mobile
Trình duyệt: Chrome, Safari, Firefox
Yêu cầu bổ sung:
Đảm bảo rằng mọi thay đổi đều không làm ảnh hưởng đến tính năng hiện tại của website.
Kiểm tra lại hiệu suất bằng công cụ như Lighthouse sau khi tối ưu để đảm bảo cải thiện.
Tài liệu tham khảo:
React Code Splitting
Lazy Loading Images in React
Ưu tiên: Cao
![{1AB28583-40F0-4CB6-9804-3D59C43D507E}](https://github.com/user-attachments/assets/f8f7b072-a34f-4f2b-95ae-26a5c8ec9c17)

**Comment by HDV2k3** [comment]
hãy xem xét cho tôi issue  trên

**Comment by NamDuongPham** [comment]
![image](https://github.com/user-attachments/assets/97eb656a-917c-434d-b6c6-fa63ebfef733)
tôi đã sửa chữa performance

**Comment by NamDuongPham** [comment]
cảm ơn bạn đã góp ý
